version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - mern-app
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
